version: '3'

networks:
  marketplace-project:
    #      name: 50_default
    driver: bridge

services:

  marketplace-project:
    build:
      dockerfile: Dockerfile
    container_name: marketplace-project
    networks:
      - marketplace-project
    volumes:
      - '.:/var/www/html'
      - '/mnt/var:/mnt/var'
    ports:
      - "8096:80"

###> doctrine/doctrine-bundle ###
  marketplace-database:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: marketplace-mysql-dwh
    restart: always
    environment:
      MYSQL_DATABASE: "marketplacemarketplace"
      MYSQL_USER: "marketplaceUser"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    ports:
      - "3312:3306"
    volumes:
      - marketplace_dwh:/var/lib/mysql
    networks:
      - marketplace-project

  marketplace-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: marketplace-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: Kimpa
      MYSQL_DATABASE: marketplacemarketplace
      MYSQL_USER: marketplaceUser
      MYSQL_PASSWORD: 123
      PMA_HOST: marketplace-database
    restart: always
    networks:
      - marketplace-project
    ports:
      - 8083:80

volumes:
###> doctrine/doctrine-bundle ###
  marketplace_dwh:

  marketplace_test_dwh:
